version: '3'

services:
  gateway:
    image: ramsgoli/gateway
  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  thegoonlagoon-app:
    image: ramsgoli/thegoonlagoon-app
    env_file: .env

volumes:
  postgres-data:

